project:
  type: website

website:
  title: "AD-688 Team 4 – Data Science & BA Trends"
  navbar:
    left:
      - href: index.qmd
        text: Home
<<<<<<< HEAD
      - href: data_analysis.qmd
        text: "Data Analysis"
=======
      - href: analysis.qmd
        text: Analysis
      - href: data_analysis.qmd
        text: Data Cleaning
>>>>>>> 3b1fa348e01656f24c07a8a962a3e371c9ca874a
      - href: career_plan.qmd
        text: "Career Strategy"

format:
  html:
    theme: cosmo
    toc: true