project:
  type: website

website:
  title: "AD-688 Team 4 – Data Science & BA Trends"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: analysis.qmd
        text: Analysis
      - href: data_analysis.qmd
        text: Data Cleaning
<<<<<<< HEAD
      - href: eda.qmd 
=======
      - href: eda.qmd
>>>>>>> 71fa5d5 (Updated navbar)
        text: "Exploratory Analysis"
      - href: career_plan.qmd
        text: "Career Strategy"

format:
  html:
    theme: cosmo
    toc: true